// https://drafts.csswg.org/css-font-loading/#typedefdef-binarydata
typedef (ArrayBuffer or ArrayBufferView) BinaryData;

// https://drafts.csswg.org/css-font-loading/#dictdef-fontfacedescriptors
dictionary FontFaceDescriptors {
    CSSOMString style = "normal";
    CSSOMString weight = "normal";
    CSSOMString stretch = "normal";
    CSSOMString unicodeRange = "U+0-10FFFF";
    CSSOMString featureSettings = "normal";
    CSSOMString variationSettings = "normal";
    CSSOMString display = "auto";
    CSSOMString ascentOverride = "normal";
    CSSOMString descentOverride = "normal";
    CSSOMString lineGapOverride = "normal";
};

// https://drafts.csswg.org/css-font-loading/#fontface-interface
[Exposed=(Window,Worker)]
interface FontFace {
    constructor(CSSOMString family, CSSOMString source, 
                optional FontFaceDescriptors descriptors = {});
    
    [ImplementedAs=font_family]readonly attribute CSSOMString family;
};
